# Generated by Django 2.0.4 on 2018-06-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20180610_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='final_duration',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='initial_duration',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_left',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
